#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

#Install nginx
sudo apt -y update
sudo apt install -y nginx

#Configuration
mkdir /etc/nginx/html

#Creating Sample Page
echo "Hello World!" > /etc/nginx/html/index.html

#Create Server Block
echo "server {
        listen 80 default_server;
	listen [::]:80 default_server;

	root /etc/nginx/html;
	index index html index.htm index nginx-debian.html;

	server_name -.
}
" > /etc/nginx/sites-available/default

#Restart Ngnix
nginx -s reload
